tabItem_main <- tabItem(
  "tab_main",
  tags$head(tags$style(HTML(".h3 {margin-left:15px}"))),
  h2("Functions"),
  h3("Graph"),
  p("In the Graph tab, you can search genes by annotation, and then create ggplot graphs using RNAseq datasets."),
  h3("Heatmap"),
  p("In Heatmap tab, you can search a geneset by annotation, and create heatmap using a paricular RNAseq dataset."),
  h3("MSA (Muliple Sequence Alingnment)"),
  p("In MSA tab, you can get the multi fasta, MSA, and gene tree of an ortholog group. The MSA include Arabidopsis, Tomato, Snapdragon, and Yellow monkyflower, as well as four Callitriche species."),
  h3("C.deflexa"),
  p("In C. deflexa tab, you can draw the expression graph of C. deflexa leaf primordia (< 0.5 mm in length)."),
  p("The data is identical to Koga et al., 2021."),
  h2("Genome Info"),
  p("Cpal genome annotation version 2.2"),
  h2("Release Note"),
  p("2025-03-18: data updated to v2.2, system updated with SQLite"),
  p("2022-10-25: initial release"),
  h2("Citations"),
  p("TBA")
)
